# Generated by Django 4.1.7 on 2023-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=300, verbose_name='频道来源网站ID')),
                ('tvg_name', models.CharField(db_index=True, max_length=100, verbose_name='匹配用的tvg-name')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='频道显示名称')),
                ('sort', models.CharField(db_index=True, max_length=50, verbose_name='频道分类')),
                ('logo', models.CharField(max_length=400, null=True, verbose_name='台标地址')),
                ('last_program_date', models.DateField(db_index=True, null=True, verbose_name='最新节目日期')),
                ('last_crawl_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='最近的采集日期')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('descr', models.CharField(blank=True, max_length=500, null=True, verbose_name='频道描述')),
                ('has_epg', models.IntegerField(choices=[(1, '是'), (0, '否')], db_index=True, default=0, verbose_name='是否有节目表')),
                ('ineed', models.IntegerField(choices=[(1, '是'), (0, '否')], db_index=True, default=0, verbose_name='是否需获取')),
                ('source', models.CharField(choices=[('tvmao', '电视猫'), ('tvsou', '搜视'), ('cctv', '央视'), ('zhongshu', '中数'), ('tbc', '台湾宽频tbc'), ('mod', '中华电信MOD'), ('cabletv', '香港有线宽频caletv'), ('g4tv', '台湾四季电视'), ('icable', '香港有线宽频i-cable'), ('nowtv', '香港NOWTV'), ('tvb', '香港无线电视TVB'), ('smg', '上海广播电视'), ('btv', '北京卫视'), ('gdtv', '广东卫视'), ('hks', '香港卫视'), ('viu', 'viutv'), ('chuanliu', '川流TV'), ('mytvsuper', 'myTVSUPER')], db_index=True, max_length=50, null=True, verbose_name='节目来源')),
                ('recrawl', models.IntegerField(choices=[(1, '是'), (0, '否')], db_index=True, default=0, verbose_name='需重新获取当天数据')),
                ('patten', models.CharField(blank=True, max_length=100, null=True, verbose_name='本频道正则')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '频道列表',
                'verbose_name_plural': '频道列表',
            },
        ),
        migrations.CreateModel(
            name='ChannelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_channel_id', models.IntegerField(db_index=True, default=99999, verbose_name='内部id')),
                ('out_channel_id', models.CharField(max_length=100, verbose_name='来源网站上的id')),
                ('inner_name', models.CharField(max_length=20, verbose_name='内部tvg-name')),
                ('out_name', models.CharField(max_length=20, verbose_name='来源网站上的名称')),
                ('source', models.CharField(max_length=20, verbose_name='来源网站')),
                ('is_alive', models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='来源网站上是否仍然存在')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '频道来源整理表',
                'verbose_name_plural': '频道来源整理表',
                'db_table': 'web_channel_list',
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='日志时间')),
                ('msg', models.TextField(max_length=1000, verbose_name='内容')),
                ('level', models.IntegerField(choices=[(1, '信息'), (2, '错误警告')], default=1, verbose_name='日志级别')),
            ],
            options={
                'verbose_name': '抓取日志',
                'verbose_name_plural': '抓取日志',
                'db_table': 'web_crawl_log',
            },
        ),
        migrations.CreateModel(
            name='Epg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=50, verbose_name='频道ID')),
                ('starttime', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('title', models.CharField(max_length=200, verbose_name='节目名称')),
                ('descr', models.TextField(null=True, verbose_name='节目描述')),
                ('program_date', models.DateField(db_index=True, verbose_name='节目所属于日期')),
                ('crawl_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='采集时间')),
                ('source', models.CharField(max_length=20, null=True, verbose_name='节目来源')),
            ],
            options={
                'verbose_name': '节目表',
                'verbose_name_plural': '节目表',
            },
        ),
    ]
